---
letsencrypt_certificates:
  []
  #- domain: k8stest.com
  #san: ["*.k8stest.com"]
  #email: email@k8stest.com
  #mode: standalone
  #live: true

#letsencrypt_dns_ovh_application_key = MDAwMDAwMDAwMDAw
#letsencrypt_dns_ovh_application_secret = MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAw
#letsencrypt_dns_ovh_consumer_key = MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAw
