apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/name: apcups-exporter
      app.kubernetes.io/component: daemon
      app.kubernetes.io/version: 28b7412171d865777a1bb8c9358df081d50f2bba-3.22.2

resources:
  - endpoint.yaml
  - service.yaml
