watchers:
  - type: docker_registry
    repo: registry-1.docker.io
    image: zwavejs/zwave-js-ui
    tag: 11.7.0
    includes:
      - ^[0-9]+\.[0-9]+\.[0-9]+.*$
    excludes:
      - ^[1-9]\..*
      - ^10\..*
      - ^11\.[0-6]\..*
