watchers:
  - type: docker_registry
    repo: quay.io
    image: mittwald/kubernetes-replicator
    tag: v2.12.1
    includes:
      - v[0-9]+\.[0-9]+\.[0-9]+
    excludes:
      - v[0-1]\..*
      - v2\.[0-9]\..*
      - v2\.1[0-1\..*
