watchers:
  - type: docker_registry
    repo: ghcr.io
    image: blakeblackshear/frigate
    tag: 0.16.3
    includes:
      - ^[0-9]+\.[0-9]+\.[0-9]+$
    excludes:
      - ^0\.[0-9]\..*
      - ^0\.1[0-5]\..*
      - .*nvidia.*
