watchers:
  - type: docker_registry
    repo: registry-1.docker.io
    image: nginx/nginx-prometheus-exporter
    tag: 1.5.1
    includes:
      - ^[0-9]+\.[0-9]+.[0-9]+
    excludes:
      - ^0\..*
      - ^1\.[0-4]\..*
