watchers:
  - type: docker_registry
    repo: "registry-1.docker.io"
    image: "lemonldapng/lemonldap-ng"
    tag: "2.22.0"
    excludes:
      - latest
      - ^1\.
      - ^2\.0\..*
      - ^2\.1[0-9]\..*
      - ^2\.2[0-1]\..*
