watchers:
  - type: docker_registry
    repo: ghcr.io
    image: koenkk/zigbee2mqtt
    tag: 2.7.2
    includes:
      - ^[0-9]+\.[0-9]+\.[0-9]+.*$
    excludes:
      - ^[0-1]\..*
      - ^2\.[0-6]\..*
