watchers:
  - type: docker_registry
    repo: registry-1.docker.io
    image: crowdsecurity/crowdsec
    tag: v1.7.3-debian
    includes:
      - ^v[0-9]+\.[0-9]+\.[0-9]+(-[0-9]+)?-debian
    excludes:
      - ^v1\.[0-6]\.
      - ^v1\.7\.[0-2]-
