watchers:
  - type: docker_registry
    repo: registry-1.docker.io
    image: jacobalberty/unifi
    tag: v10.0.162
    includes:
      - "^v?[0-9]+\\.[0-9]+\\.[0-9]+$"
    excludes:
      - ^v?[0-9]\.
      - ^v?10\.0\.[0-9]$
      - ^v?10\.0\.[0-9][0-9]$
      - ^v?10\.0\.1[0-5][0-9]$
