watchers:
  - name: Homepage
    type: docker_registry
    repo: ghcr.io
    image: ghcr.io/gethomepage/homepage
    tag: v1.7.0
    includes:
      - ^v[0-9]+\.[0-9]+\.[0-9]+
    excludes:
      - ^v0\.
      - ^v1\.[0-6]\.
