watchers:
  - type: pypi
    package: ansible
    version: 12.2.0
    excludes:
      - .*[ab][1-9]$
      - .*rc[1-9]$
      - ^[0-9]\..*
      - ^1[0-1]\..*
      - ^12\.[0-1]\..*
  - type: github_release
    repo: mehdy/keepalived-exporter
    release: v1.7.0
  - type: github_release
    repo: kubernetes/kubernetes
    release: v1.33.4
    excludes:
      - .*(alpha|beta|rc).*
      - v1\.[0-2][0-9]\..*
  - type: github_release
    repo: cri-o/cri-o
    release: 1.33.3
    excludes:
      - .*(alpha|beta|rc).*
      - v1\.[0-2][0-9]\..*
      - v1\.3[0-2]\..*
  - type: github_release
    repo: kubernetes-sigs/kustomize
    release: kustomize/v5.8.0
    includes:
      - kustomize/.*
    excludes:
      - .*(alpha|beta|rc).*
  - type: github_release
    repo: getsops/sops
    release: v3.10.2
    excludes:
      - .*(alpha|beta|rc).*
      - v[0-2]\..*
      - v3\.[0-9]\..*
  - type: github_release
    repo: viaduct-ai/kustomize-sops
    release: v4.3.3
    excludes:
      - .*(alpha|beta|rc).*
      - v[0-3]\..*
      - v4\.[0-2]\..*
  - type: github_release
    repo: restic/restic
    release: v0.18.0
  - type: github_release
    repo: rclone/rclone
    release: v1.70.3
